# Generated by Django 5.0.7 on 2024-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coordinador', models.IntegerField()),
                ('nombres_coordinador', models.TextField()),
                ('apellidos_coordinador', models.TextField()),
                ('contraseña', models.TextField()),
                ('correo', models.TextField()),
                ('programa', models.TextField()),
                ('celular', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'coordinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_director', models.IntegerField()),
                ('nombres_director', models.TextField()),
                ('apellidos_director', models.TextField()),
                ('correo', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('contrasena', models.TextField()),
                ('id_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.IntegerField(db_column='NIT', primary_key=True, serialize=False)),
                ('nombre_empresa', models.TextField()),
                ('celular', models.IntegerField()),
                ('razon_social', models.TextField()),
                ('direccion', models.TextField()),
                ('act_economica', models.TextField()),
                ('gerente', models.TextField()),
                ('producto_servicio', models.TextField(db_column='producto/servicio')),
                ('correo', models.TextField()),
                ('pagina_web', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('ventas_ult_ano', models.IntegerField()),
                ('costos_ult_ano', models.IntegerField()),
                ('empleados_perm', models.IntegerField()),
                ('sector', models.TextField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.TextField()),
                ('escala', models.TextField()),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField()),
                ('nivel_basico', models.TextField()),
                ('estado_actual', models.TextField()),
                ('nivel_ideal', models.TextField()),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_postulante', models.TextField()),
                ('apellidos_postulante', models.TextField()),
                ('celular', models.IntegerField()),
                ('genero', models.TextField()),
                ('correo', models.TextField()),
                ('municipio', models.TextField()),
                ('no_documento', models.IntegerField()),
                ('tipo_documento', models.TextField()),
            ],
            options={
                'db_table': 'postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_director', models.IntegerField()),
            ],
            options={
                'db_table': 'programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.IntegerField()),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField()),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suenos',
            fields=[
                ('id_sueno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sueno', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('alcance', models.IntegerField()),
            ],
            options={
                'db_table': 'sue±os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'talleres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.TextField()),
                ('correo', models.TextField()),
                ('celular', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('programa', models.TextField()),
                ('contrasena', models.TextField()),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
