# Generated by Django 5.0.7 on 2024-09-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionModulo',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacion_modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoEmpresarialModulos',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('criterio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'diagnostico_empresarial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.IntegerField(db_column='nit', primary_key=True, serialize=False)),
                ('nombre_empresa', models.TextField()),
                ('celular', models.BigIntegerField()),
                ('razon_social', models.TextField()),
                ('direccion', models.TextField()),
                ('act_economica', models.TextField()),
                ('gerente', models.TextField()),
                ('producto_servicio', models.TextField(db_column='producto/servicio')),
                ('correo', models.TextField()),
                ('pagina_web', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('ventas_ult_ano', models.BigIntegerField()),
                ('costos_ult_ano', models.BigIntegerField()),
                ('empleados_perm', models.BigIntegerField()),
                ('sector', models.TextField()),
                ('estado', models.IntegerField()),
                ('diagnostico_value', models.IntegerField()),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MisePrueba',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'mise_prueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloAutoevaluacion',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_autoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('objetivo', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('observaciones', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('alcance', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('estado_actual', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('nivel_ideal', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_postulante', models.TextField()),
                ('apellidos_postulante', models.TextField()),
                ('celular', models.BigIntegerField()),
                ('genero', models.TextField()),
                ('correo', models.TextField()),
                ('municipio', models.TextField()),
                ('no_documento', models.BigIntegerField()),
                ('tipo_documento', models.TextField()),
                ('educacion', models.TextField()),
                ('cargo', models.TextField()),
            ],
            options={
                'db_table': 'postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_director', models.IntegerField()),
            ],
            options={
                'db_table': 'programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.IntegerField()),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField()),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('sueño', models.TextField()),
                ('medicion', models.TextField()),
                ('fortalecimiento', models.TextField()),
                ('evidencia', models.TextField()),
            ],
            options={
                'db_table': 'suenos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'talleres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_formacion', models.CharField(max_length=255)),
                ('num_sesion', models.IntegerField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('alcance', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('conferencista', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'temas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemasPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'temas_preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
                ('correo', models.TextField()),
                ('celular', models.BigIntegerField()),
                ('documento', models.BigIntegerField()),
                ('programa', models.TextField()),
                ('contrasena', models.TextField(db_collation='utf8mb4_0900_ai_ci')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escala1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('No Desarrollado', 'No Desarrollado'), ('Parcialmente Desarrollado', 'Parcialmente Desarrollado'), ('Ampliamente Desarrollado', 'Ampliamente Desarrollado'), ('No Aplica', 'No Aplica')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=50)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='users.modulos')),
                ('nit', models.ForeignKey(db_column='nit', on_delete=django.db.models.deletion.CASCADE, to='users.empresas')),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresas')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulos')),
            ],
            options={
                'db_table': 'diagnosticoempresarial',
            },
        ),
        migrations.CreateModel(
            name='Escalas',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('rango_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rango_maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('id_modulo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.modulos')),
            ],
            options={
                'db_table': 'escalas',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresas')),
                ('modulo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulo1')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('modulo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas1', to='users.modulo1')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas1', to='users.diagnostico1')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.escala1')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas1', to='users.pregunta1')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoEmpresarialSuenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.diagnosticoempresarial')),
                ('sueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.suenos')),
            ],
            options={
                'db_table': 'diagnosticosuenos',
                'indexes': [models.Index(fields=['diagnostico', 'sueno'], name='diagnostico_diagnos_133e50_idx')],
                'unique_together': {('diagnostico', 'sueno')},
            },
        ),
    ]
