# Generated by Django 5.0.7 on 2024-08-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisePrueba',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'mise_prueba',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Coordinador',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AlterModelTable(
            name='suenos',
            table='suenos',
        ),
    ]
