# Generated by Django 5.0.7 on 2024-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoempresarialsuenos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
