# Generated by Django 5.0.7 on 2024-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_miseprueba_delete_coordinador_delete_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionModulo',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacion_modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloAutoevaluacion',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_autoevaluacion',
                'managed': False,
            },
        ),
    ]
