# Generated by Django 5.0.7 on 2024-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_autoevaluacion_calificacionmodulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.TextField()),
                ('titulo', models.TextField()),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('horario', models.DateField()),
                ('ubicacion', models.TextField()),
            ],
            options={
                'db_table': 'temas',
                'managed': False,
            },
        ),
    ]
