# Generated by Django 5.0.7 on 2024-09-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_temas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalas',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'escalas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escala1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('No Desarrollado', 'No Desarrollado'), ('Parcialmente Desarrollado', 'Parcialmente Desarrollado'), ('Ampliamente Desarrollado', 'Ampliamente Desarrollado'), ('No Aplica', 'No Aplica')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresas')),
                ('modulo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulo1')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('modulo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas1', to='users.modulo1')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas1', to='users.diagnostico1')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.escala1')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas1', to='users.pregunta1')),
            ],
        ),
    ]
