# Generated by Django 5.0.7 on 2024-09-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_escalas_evaluaciones_escala1_modulo1_diagnostico1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalas',
            options={},
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='users.preguntas')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='users.empresas')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulos')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='users.empresas')),
            ],
            options={
                'db_table': 'diagnosticos',
            },
        ),
    ]
