# Generated by Django 5.0.7 on 2024-09-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_escalas_options_calificaciones_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='fecha_diagnostico',
        ),
        migrations.AddField(
            model_name='escalas',
            name='id_modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.modulos'),
        ),
        migrations.AddField(
            model_name='escalas',
            name='rango_maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='escalas',
            name='rango_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='id_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='users.modulos'),
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='diagnostico',
        ),
    ]
