# Generated by Django 5.0.7 on 2024-09-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_diagnostico_fecha_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='nit',
            field=models.ForeignKey(db_column='nit', on_delete=django.db.models.deletion.CASCADE, to='users.empresas'),
        ),
    ]
