# Generated by Django 5.0.7 on 2024-09-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_diagnostico_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='nit',
            field=models.ForeignKey(db_column='nit', on_delete=django.db.models.deletion.CASCADE, to='users.empresas'),
        ),
    ]
