# Generated by Django 5.0.7 on 2024-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_calificaciones_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nit',
            field=models.CharField(max_length=20),
        ),
    ]
