# Generated by Django 5.0.7 on 2024-09-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_calificaciones_id_alter_calificaciones_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificaciones',
            options={'managed': False},
        ),
    ]
