# Generated by Django 5.0.7 on 2024-09-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_calificaciones_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoEmpresarial',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('criterio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'diagnostico_empresarial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemasPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'temas_preguntas',
                'managed': False,
            },
        ),
    ]
