# Generated by Django 5.0.7 on 2024-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id_coordinador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_coordinador', models.TextField()),
                ('apellidos_coordinador', models.TextField()),
                ('contraseña', models.TextField()),
                ('correo', models.TextField()),
                ('programa', models.TextField()),
                ('celular', models.IntegerField()),
                ('documento', models.IntegerField()),
            ],
            options={
                'db_table': 'coordinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_director', models.TextField()),
                ('apellidos_director', models.TextField()),
                ('correo', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('contraseña', models.TextField()),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.IntegerField(db_column='NIT', primary_key=True, serialize=False)),
                ('nombre_empresa', models.TextField()),
                ('celular', models.IntegerField()),
                ('razon_social', models.TextField()),
                ('direccion', models.TextField()),
                ('act_economica', models.TextField()),
                ('gerente', models.TextField()),
                ('producto_servicio', models.TextField(db_column='producto/servicio')),
                ('correo', models.TextField()),
                ('pagina_web', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('ventas_ult_año', models.IntegerField()),
                ('costos_ult_año', models.IntegerField()),
                ('empleados_perm', models.IntegerField()),
                ('sector', models.TextField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MisePrueba',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'mise_prueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.TextField()),
                ('escala', models.TextField()),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField()),
                ('nivel_basico', models.TextField()),
                ('estado_actual', models.TextField()),
                ('nivel_ideal', models.TextField()),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_postulante', models.TextField()),
                ('apellidos_postulante', models.TextField()),
                ('celular', models.IntegerField()),
                ('genero', models.TextField()),
                ('correo', models.TextField()),
                ('municipio', models.TextField()),
                ('no_documento', models.IntegerField()),
                ('tipo_documento', models.TextField()),
            ],
            options={
                'db_table': 'postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_director', models.IntegerField()),
            ],
            options={
                'db_table': 'programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.IntegerField()),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField()),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sueños',
            fields=[
                ('id_sueño', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sueño', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('alcance', models.IntegerField()),
            ],
            options={
                'db_table': 'sue±os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.TextField()),
                ('criterio', models.TextField()),
            ],
            options={
                'db_table': 'talleres',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
