# Generated by Django 5.0.7 on 2024-08-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_coordinador_director_empresas_miseprueba_modulos_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuario',
        ),
    ]
